# .github/FUNDING.yml

github: []  # You can skip if you're not using GitHub Sponsors
patreon: []
open_collective: []
ko_fi: your_kofi_username
buy_me_a_coffee: your_bmac_username
custom: ['https://your-project.com/sponsor']
