// src/types/workflow.ts
export interface FileChangeEntry {
	filePath: string; // Relative path to the workspace root
	changeType: "created" | "modified" | "deleted"; // Type of change
	summary: string; // Human-readable summary generated by diffingUtils
	timestamp: number; // Unix timestamp for chronological ordering
	addedLines?: string[];
	removedLines?: string[];
}
