import * as vscode from "vscode";
import * as path from "path";
import * as crypto from "crypto";
import { AIRequestService } from "../services/aiRequestService";
import {
	ContextService,
	ActiveSymbolDetailedInfo,
} from "../services/contextService";
import { cleanCodeOutput } from "../utils/codeUtils";
import { DiagnosticService, getSeverityName } from "../utils/diagnosticUtils";
import { generateFileChangeSummary } from "../utils/diffingUtils";
import { ExtensionToWebviewMessages } from "../sidebar/common/sidebarTypes";
import { ProjectChangeLogger } from "../workflow/ProjectChangeLogger";
import { RevertibleChangeSet } from "../types/workflow";

// NEW IMPORTS FOR PROMPT GENERATOR FUNCTIONS
import {
	createEnhancedGenerationPrompt,
	createRefinementPrompt,
	createEnhancedModificationPrompt,
	createRefineModificationPrompt,
	createAlternativeCorrectionPrompt,
	createSyntaxCorrectionPrompt,
	createImportCorrectionPrompt,
	createPracticeCorrectionPrompt,
	createSecurityCorrectionPrompt,
	createAIFailureAnalysisPrompt,
} from "./prompts/enhancedCodeGenerationPrompts";

/**
 * Real-time feedback interface for code generation
 */
interface RealTimeFeedback {
	stage: string;
	message: string;
	issues: CodeIssue[];
	suggestions: string[];
	progress: number; // 0-100
}

export interface CodeValidationResult {
	isValid: boolean;
	finalContent: string;
	issues: CodeIssue[];
	suggestions: string[];
	iterations?: number;
	totalIssues?: number;
	resolvedIssues?: number;
}

export interface CodeIssue {
	type: "syntax" | "unused_import" | "best_practice" | "security" | "other";
	message: string;
	line: number;
	severity: "error" | "warning" | "info";
	code?: string | number;
}

export interface FileAnalysis {
	framework: string;
	projectStructure: string;
	expectedPatterns: string;
	fileName: string;
	extension: string;
}

export interface FileStructureAnalysis {
	imports: Array<{ line: number; content: string }>;
	exports: Array<{ line: number; content: string }>;
	functions: Array<{ line: number; content: string }>;
	classes: Array<{ line: number; content: string }>;
	variables: Array<{ line: number; content: string }>;
	comments: Array<{ line: number; content: string }>;
}

export interface DiffAnalysis {
	isReasonable: boolean;
	issues: string[];
	changeRatio: number;
}

/**
 * Encapsulates details about a single correction attempt that did not yield the desired result.
 */
export interface CorrectionAttemptOutcome {
	success: boolean; // Indicates whether the correction attempt resulted in an improvement or at least maintained the status quo
	iteration: number; // The specific iteration number within the _generateWithRealTimeFeedback loop
	originalIssuesCount: number; // The number of issues identified before this correction attempt
	issuesAfterAttemptCount: number; // The number of issues identified after this correction attempt
	issuesRemaining: CodeIssue[]; // A list of CodeIssue objects that were still present after the attempt
	issuesIntroduced: CodeIssue[]; // A list of *new* CodeIssue objects introduced by this attempt
	relevantDiff: string; // The generated code diff representing the changes made in this attempt
	aiFailureAnalysis: string; // The crucial textual diagnosis generated by the AI itself, explaining *why* it believes the attempt failed
	failureType:
		| "no_improvement"
		| "new_errors_introduced"
		| "parsing_failed"
		| "unreasonable_diff"
		| "command_failed"
		| "unknown"; // A categorical reason for the failure
}

// NEW: Define EnhancedGenerationContext interface
export interface EnhancedGenerationContext {
	projectContext: string;
	relevantSnippets: string;
	editorContext?: any;
	activeSymbolInfo?: ActiveSymbolDetailedInfo;
	fileStructureAnalysis?: FileStructureAnalysis;
	lastFailedCorrectionDiff?: string;
	successfulChangeHistory?: string; // NEW: Added property
	lastCorrectionAttemptOutcome?: CorrectionAttemptOutcome; // NEW: Added property
	recentCorrectionAttemptOutcomes?: CorrectionAttemptOutcome[]; // NEW: Added property
	isOscillating?: boolean; // NEW: Added property
	relevantFiles?: string; // NEW: Added property as per instructions
	isRewriteOperation?: boolean; // NEW: Added property to indicate rewrite intent
}

/**
 * Get language ID from file extension
 */
function getLanguageId(extension: string): string {
	const languageMap: Record<string, string> = {
		".ts": "typescript",
		".tsx": "typescript",
		".js": "javascript",
		".jsx": "javascript",
		".py": "python",
		".java": "java",
		".cs": "csharp",
		".cpp": "cpp",
		".c": "c",
		".go": "go",
		".rs": "rust",
		".php": "php",
		".rb": "ruby",
		".swift": "swift",
		".kt": "kotlin",
	};

	return languageMap[extension] || "text";
}

/**
 * Extracts a code snippet around a given line number.
 * @param fullContent The full string content of the file.
 * @param lineNumber The 1-indexed line number to center the snippet around.
 * @param linesBefore The number of lines to include before the target line.
 * @param linesAfter The number of lines to include after the target line.
 * @returns A string containing the formatted code snippet.
 */
function getCodeSnippet(
	fullContent: string,
	lineNumber: number,
	linesBefore: number = 2,
	linesAfter: number = 2
): string {
	const lines = fullContent.split("\n");
	const zeroBasedLineNumber = lineNumber - 1; // Convert to 0-indexed

	const start = Math.max(0, zeroBasedLineNumber - linesBefore);
	const end = Math.min(lines.length - 1, zeroBasedLineNumber + linesAfter);

	const snippetLines: string[] = [];
	const maxLineNumLength = String(end + 1).length; // For padding

	for (let i = start; i <= end; i++) {
		const currentLineNum = i + 1; // Convert back to 1-indexed for display
		const paddedLineNum = String(currentLineNum).padStart(
			maxLineNumLength,
			" "
		);
		snippetLines.push(`${paddedLineNum}: ${lines[i]}`);
	}

	return snippetLines.join("\n");
}

/**
 * Groups and prioritizes code issues for prompt generation.
 * Issues are grouped by a combination of type, severity, and specific code (if applicable).
 * Priorities are based on predefined orders (`issueTypeOrder`, `severityOrder`).
 * Special handling for 'cannot find name' errors by grouping them by the missing identifier.
 * @param issues An array of CodeIssue objects.
 * @returns A Map where keys are formatted group headers and values are arrays of CodeIssue.
 */
function groupAndPrioritizeIssues(
	issues: CodeIssue[],
	issueTypeOrder: CodeIssue["type"][],
	severityOrder: CodeIssue["severity"][]
): Map<string, CodeIssue[]> {
	const groupedIssues = new Map<string, CodeIssue[]>();

	// Sort issues initially based on predefined order and then line number
	issues.sort((a, b) => {
		const typeOrderA = issueTypeOrder.indexOf(a.type);
		const typeOrderB = issueTypeOrder.indexOf(b.type);
		if (typeOrderA !== typeOrderB) {
			return typeOrderA - typeOrderB;
		}

		const severityOrderA = severityOrder.indexOf(a.severity);
		const severityOrderB = severityOrder.indexOf(b.severity);
		if (severityOrderA !== severityOrderB) {
			return severityOrderA - severityOrderB;
		}

		return a.line - b.line;
	});

	for (const issue of issues) {
		let groupKey = "";
		// Special grouping for 'cannot find name' errors
		if (
			issue.message.includes("Cannot find name") &&
			issue.type === "syntax" &&
			issue.severity === "error"
		) {
			const match = issue.message.match(/Cannot find name '([^']*)'/);
			const missingName = match ? match[1] : "unknown_identifier"; // Use "unknown_identifier" for clarity
			groupKey = `TYPE: ${issue.type.toUpperCase()} / SEVERITY: ${issue.severity.toUpperCase()} / ISSUE: Missing Identifier '${missingName}'`;
		} else {
			groupKey = `TYPE: ${issue.type.toUpperCase()} / SEVERITY: ${issue.severity.toUpperCase()}${
				issue.code ? ` / CODE: ${issue.code}` : ""
			}`;
		}

		if (!groupedIssues.has(groupKey)) {
			groupedIssues.set(groupKey, []);
		}
		groupedIssues.get(groupKey)!.push(issue);
	}

	return groupedIssues;
}

/**
 * Formats grouped and prioritized issues into a Markdown string for AI prompts.
 * @param groupedIssues A Map of grouped CodeIssue objects.
 * @param languageId The language ID of the file (e.g., 'typescript', 'javascript').
 * @param content The full content of the file to extract code snippets.
 * @returns A formatted Markdown string representing the issues.
 */
function formatGroupedIssuesForPrompt(
	groupedIssues: Map<string, CodeIssue[]>,
	languageId: string,
	content: string,
	issueTypeOrder: CodeIssue["type"][],
	severityOrder: CodeIssue["severity"][],
	getCodeSnippetFn: (
		content: string,
		lineNumber: number,
		linesBefore?: number,
		linesAfter?: number
	) => string
): string {
	let formattedString = "";

	// Sort group keys based on issue type and severity order
	const sortedGroupKeys = Array.from(groupedIssues.keys()).sort(
		(keyA, keyB) => {
			const issueTypeA =
				issueTypeOrder.find((type) =>
					keyA.includes(`TYPE: ${type.toUpperCase()}`)
				) || "other";
			const issueTypeB =
				issueTypeOrder.find((type) =>
					keyB.includes(`TYPE: ${type.toUpperCase()}`)
				) || "other";
			const typeOrderResult =
				issueTypeOrder.indexOf(issueTypeA as CodeIssue["type"]) -
				issueTypeOrder.indexOf(issueTypeB as CodeIssue["type"]);
			if (typeOrderResult !== 0) {
				return typeOrderResult;
			}

			const severityA =
				severityOrder.find((severity) =>
					keyA.includes(`SEVERITY: ${severity.toUpperCase()}`)
				) || "info";
			const severityB =
				severityOrder.find((severity) =>
					keyB.includes(`SEVERITY: ${severity.toUpperCase()}`)
				) || "info";
			return (
				severityOrder.indexOf(severityA as CodeIssue["severity"]) -
				severityOrder.indexOf(severityB as CodeIssue["severity"])
			);
		}
	);

	for (const groupKey of sortedGroupKeys) {
		const issuesInGroup = groupedIssues.get(groupKey)!;
		formattedString += `--- Issue Group: ${groupKey} ---\n`;

		// Add suggested strategy for the group
		let suggestedStrategy =
			"Review the provided code snippet and diagnostic message. Apply the most targeted fix to resolve this specific issue while adhering to all critical requirements.";
		if (groupKey.includes("ISSUE: Missing Identifier")) {
			suggestedStrategy =
				"Suggested Strategy: This group contains 'Cannot find name' errors, indicating a missing identifier. This almost always means a missing import statement, a typo in a variable/function/type name, or an undeclared variable/constant. Your specific action should be: 1. **Check Imports**: Verify if the missing identifier is an external dependency or a local module export; add the necessary import statement if it's missing. 2. **Check Typos**: Meticulously review the spelling of the identifier in both its usage and declaration. 3. **Check Scope/Declaration**: Ensure the identifier is declared and accessible within the current scope. If it's an undeclared variable, declare it with the correct type. Pay close attention to case sensitivity.";
		} else if (groupKey.includes("TYPE: UNUSED_IMPORT")) {
			suggestedStrategy =
				"Suggested Strategy: This group contains unused import warnings. This indicates an an import statement that is no longer being used by any code within the file. Your specific action should be: 1. **Remove Statement**: Delete the entire unused import statement. 2. **Verify No Reliance**: Before removal, quickly scan the file to ensure no other code unexpectedly relies on this import (e.g., dynamic usage not caught by static analysis).";
		} else if (groupKey.includes("TYPE: SECURITY")) {
			suggestedStrategy =
				"Suggested Strategy: This group contains security issues or vulnerabilities. Your specific action should be: 1. **Implement Secure Practices**: Apply standard secure coding practices relevant to the language and context (e.g., input validation, output encoding, proper authentication/authorization, secure data handling). 2. **Mitigate Vulnerability**: Directly address the vulnerability described in the message (e.g., prevent XSS, SQL injection, path traversal).";
		} else if (groupKey.includes("TYPE: BEST_PRACTICE")) {
			suggestedStrategy =
				"Suggested Strategy: This group contains best practice issues. These are typically suggestions for improving code quality, readability, maintainability, or performance, rather than critical errors. Your specific action should be: 1. **Refine Code**: Refactor small sections to align with established coding patterns, improve naming conventions, or use more idiomatic language features. 2. **Enhance Readability/Maintainability**: Focus on clarity, simplicity, and consistency without introducing new bugs.";
		} else if (
			groupKey.includes("TYPE: SYNTAX") &&
			groupKey.includes("ERROR")
		) {
			suggestedStrategy =
				"Suggested Strategy: This group contains critical syntax errors that prevent the code from compiling or parsing correctly. Your specific action should be: 1. **Correct Exact Mistake**: Focus solely on fixing the precise syntax mistake indicated by the diagnostic message (e.g., missing semicolon, incorrect keyword usage, mismatched parentheses/braces, incorrect function signature). 2. **Minimal Changes**: Ensure changes are localized and do not affect surrounding correct code.";
		} else if (groupKey.includes("TYPE: OTHER")) {
			suggestedStrategy =
				"Suggested Strategy: This group contains general or uncategorized issues. While not falling into specific categories, they still require attention. Your specific action should be: 1. **Analyze Message**: Carefully read the diagnostic message and examine the problematic code snippet. 2. **Precise Fix**: Apply a targeted and precise fix that directly resolves the issue without introducing unnecessary changes or side effects.";
		}
		formattedString += `Suggested Strategy: ${suggestedStrategy}\n`;

		for (const issue of issuesInGroup) {
			formattedString += `--- Individual Issue Details ---\n`;
			formattedString += `Severity: ${issue.severity.toUpperCase()}\n`;
			formattedString += `Type: ${issue.type}\n`;
			formattedString += `Line: ${issue.line}\n`;
			formattedString += `Message: ${issue.message}\n`;
			if (issue.code) {
				formattedString += `Issue Code: ${issue.code}\n`;
			}
			formattedString += `Problematic Code Snippet:\n`;
			formattedString += `\`\`\`${languageId}\n`;
			formattedString += `${getCodeSnippetFn(content, issue.line)}\n`;
			formattedString += `\`\`\`\n`;
			formattedString += `--- End Individual Issue Details ---\n\n`;
		}
		formattedString += "\n"; // Add extra newline between groups
	}

	return formattedString;
}

/**
 * Enhanced code generation with improved accuracy through:
 * 1. Better context analysis
 * 2. Code validation and refinement
 * 3. Dependency analysis
 * 4. Style consistency enforcement
 * 5. Error prevention
 * 6. Inline edit support for precise modifications
 * 7. Real-time feedback loop for immediate validation
 */
export class EnhancedCodeGenerator {
	// NEW: Define issue ordering constants
	private readonly issueTypeOrder: CodeIssue["type"][] = [
		"syntax",
		"unused_import",
		"security",
		"best_practice",
		"other",
	];
	private readonly severityOrder: CodeIssue["severity"][] = [
		"error",
		"warning",
		"info",
	];

	private readonly MAX_OSCILLATION_HISTORY_SIZE = 3; // Number of recent failed attempts to keep in context for oscillation detection

	constructor(
		private aiRequestService: AIRequestService,
		private workspaceRoot: vscode.Uri,
		private postMessageToWebview: (message: ExtensionToWebviewMessages) => void,
		private changeLogger: ProjectChangeLogger, // MODIFIED: Add changeLogger parameter
		private contextService: ContextService, // NEW: Add contextService parameter
		private config: {
			enableRealTimeFeedback?: boolean;
			maxFeedbackIterations?: number;
		} = {}
	) {
		// Set defaults
		this.config.enableRealTimeFeedback =
			this.config.enableRealTimeFeedback ?? true;
		this.config.maxFeedbackIterations = this.config.maxFeedbackIterations ?? 5;
	}

	/**
	 * Enhanced file content generation with real-time feedback loop
	 */
	public async generateFileContent(
		filePath: string,
		generatePrompt: string,
		context: EnhancedGenerationContext, // MODIFIED: Change context type
		modelName: string,
		token?: vscode.CancellationToken,
		feedbackCallback?: (feedback: RealTimeFeedback) => void,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<{ content: string; validation: CodeValidationResult }> {
		const languageId = getLanguageId(path.extname(filePath));
		const streamId = crypto.randomUUID();

		this.postMessageToWebview({
			type: "codeFileStreamStart",
			value: { streamId: streamId, filePath: filePath, languageId: languageId },
		});

		try {
			// Determine rewrite intent early
			const isRewriteOperation = this._isRewriteIntentDetected(
				generatePrompt,
				filePath
			);
			const contextForGeneration: EnhancedGenerationContext = {
				...context,
				isRewriteOperation: isRewriteOperation,
			};

			if (this.config.enableRealTimeFeedback) {
				const result = await this._generateWithRealTimeFeedback(
					filePath,
					generatePrompt,
					contextForGeneration,
					modelName,
					streamId,
					token,
					feedbackCallback,
					onCodeChunkCallback
				);
				this.postMessageToWebview({
					type: "codeFileStreamEnd",
					value: { streamId: streamId, filePath: filePath, success: true },
				});
				return result;
			} else {
				// Non-real-time feedback path also needs initial context setup.
				// This branch is rarely used in practice with `enableRealTimeFeedback` typically true.
				const fileStructureAnalysis = await this._analyzeFileStructure(
					filePath,
					"" // Pass empty string as content is not yet generated
				);
				const successfulChangeHistory = this._formatSuccessfulChangesForPrompt(
					this.changeLogger.getCompletedPlanChangeSets()
				);
				const initialGenerationContext: EnhancedGenerationContext = {
					...contextForGeneration, // Use context with isRewriteOperation
					fileStructureAnalysis: fileStructureAnalysis,
					successfulChangeHistory: successfulChangeHistory,
					lastFailedCorrectionDiff: undefined, // No failed diff yet
				};

				const initialContent = await this._generateInitialContent(
					filePath,
					generatePrompt,
					initialGenerationContext,
					modelName,
					streamId,
					token,
					onCodeChunkCallback
				);

				const validation = await this._validateAndRefineContent(
					filePath,
					initialContent,
					initialGenerationContext, // Pass context with structured analysis
					modelName,
					streamId,
					token,
					onCodeChunkCallback
				);

				const result = {
					content: validation.finalContent,
					validation,
				};
				this.postMessageToWebview({
					type: "codeFileStreamEnd",
					value: { streamId: streamId, filePath: filePath, success: true },
				});
				return result;
			}
		} catch (error: any) {
			this.postMessageToWebview({
				type: "codeFileStreamEnd",
				value: {
					streamId: streamId,
					filePath: filePath,
					success: false,
					error: error instanceof Error ? error.message : String(error),
				},
			});
			throw error;
		}
	}

	/**
	 * Enhanced file modification with intelligent diff analysis and inline edit support
	 */
	public async modifyFileContent(
		filePath: string,
		modificationPrompt: string,
		currentContent: string,
		context: EnhancedGenerationContext, // MODIFIED: Change context type
		modelName: string,
		token?: vscode.CancellationToken,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<{ content: string; validation: CodeValidationResult }> {
		const languageId = getLanguageId(path.extname(filePath));
		const streamId = crypto.randomUUID();

		this.postMessageToWebview({
			type: "codeFileStreamStart",
			value: { streamId: streamId, filePath: filePath, languageId: languageId },
		});

		try {
			// Determine rewrite intent early
			const isRewriteOperation = this._isRewriteIntentDetected(
				modificationPrompt,
				filePath
			);
			const contextForModification: EnhancedGenerationContext = {
				...context,
				isRewriteOperation: isRewriteOperation,
			};

			const result = await this._modifyFileContentFull(
				filePath,
				modificationPrompt,
				currentContent,
				contextForModification, // Pass context with isRewriteOperation
				modelName,
				streamId,
				token,
				onCodeChunkCallback
			);
			this.postMessageToWebview({
				type: "codeFileStreamEnd",
				value: { streamId: streamId, filePath: filePath, success: true },
			});
			return result;
		} catch (error: any) {
			this.postMessageToWebview({
				type: "codeFileStreamEnd",
				value: {
					streamId: streamId,
					filePath: filePath,
					success: false,
					error: error instanceof Error ? error.message : String(error),
				},
			});
			throw error;
		}
	}

	/**
	 * Generate initial content with enhanced context analysis
	 */
	private async _generateInitialContent(
		filePath: string,
		generatePrompt: string,
		context: EnhancedGenerationContext, // MODIFIED: Change context type
		modelName: string,
		streamId: string,
		token?: vscode.CancellationToken,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<string> {
		const fileExtension = path.extname(filePath);
		const languageId = getLanguageId(fileExtension);

		// Enhanced prompt with better context analysis
		const enhancedPrompt = createEnhancedGenerationPrompt(
			// Replaced `this._createEnhancedGenerationPrompt`
			filePath,
			generatePrompt,
			context
		);

		try {
			const rawContent = await this.aiRequestService.generateWithRetry(
				[{ text: enhancedPrompt }], // Modified: Wrap prompt string in HistoryEntryPart array
				modelName,
				undefined,
				"enhanced file generation",
				undefined,
				{
					onChunk: async (chunk: string) => {
						this.postMessageToWebview({
							type: "codeFileStreamChunk",
							value: { streamId: streamId, filePath: filePath, chunk: chunk },
						});
						if (onCodeChunkCallback) {
							await onCodeChunkCallback(chunk);
						}
					},
				},
				token
			);

			return cleanCodeOutput(rawContent);
		} catch (error: any) {
			throw error;
		}
	}

	/**
	 * Validate and refine generated content
	 */
	private async _validateAndRefineContent(
		filePath: string,
		content: string,
		context: EnhancedGenerationContext, // MODIFIED: Change context type
		modelName: string,
		streamId: string,
		token?: vscode.CancellationToken,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<CodeValidationResult> {
		const validation = await this._validateCode(filePath, content);

		if (validation.isValid) {
			return {
				isValid: true,
				finalContent: content,
				issues: [],
				suggestions: validation.suggestions,
			};
		}

		// Refine content if validation failed
		const refinedContent = await createRefinementPrompt(
			// Replaced `await this._refineContent(...)`
			filePath,
			content,
			validation.issues,
			context
		);

		const finalValidation = await this._validateCode(filePath, refinedContent);

		return {
			isValid: finalValidation.isValid,
			finalContent: refinedContent,
			issues: finalValidation.issues,
			suggestions: finalValidation.suggestions,
		};
	}

	/**
	 * Validate code for common issues
	 */
	private async _validateCode(
		filePath: string,
		content: string
	): Promise<CodeValidationResult> {
		const issues: CodeIssue[] = [];
		const suggestions: string[] = [];
		let hasError = false;

		const fileUri = vscode.Uri.file(filePath);
		const diagnostics = DiagnosticService.getDiagnosticsForUri(fileUri);

		for (const diag of diagnostics) {
			const severityName = getSeverityName(diag.severity);
			let issueSeverity: CodeIssue["severity"];
			let issueType: CodeIssue["type"];

			// Map VS Code severity to CodeIssue severity
			if (severityName === "Error") {
				issueSeverity = "error";
				hasError = true;
			} else if (severityName === "Warning") {
				issueSeverity = "warning";
			} else {
				issueSeverity = "info";
			}

			// Map VS Code diagnostic to CodeIssue type (prioritize specific types, then broad categories)
			const messageLower = diag.message.toLowerCase();
			if (messageLower.includes("unused import")) {
				issueType = "unused_import";
			} else if (
				issueSeverity === "error" ||
				issueSeverity === "warning" ||
				messageLower.includes("syntax") ||
				messageLower.includes("compilation") ||
				messageLower.includes("lint")
			) {
				issueType = "syntax"; // General compilation/linting issues
			} else if (messageLower.includes("security")) {
				issueType = "security"; // Explicitly map security if mentioned
			} else if (messageLower.includes("best practice")) {
				issueType = "best_practice"; // Explicitly map best practice if mentioned
			} else {
				issueType = "other"; // General fallback
			}

			let issueCode: string | number | undefined;
			if (
				typeof diag.code === "object" &&
				diag.code !== null &&
				"value" in diag.code
			) {
				issueCode = (diag.code as { value: string | number }).value;
			} else if (
				typeof diag.code === "string" ||
				typeof diag.code === "number"
			) {
				issueCode = diag.code;
			}

			issues.push({
				type: issueType,
				message: diag.message,
				line: diag.range.start.line + 1, // VS Code diagnostics are 0-indexed, CodeIssue is 1-indexed
				severity: issueSeverity,
				code: issueCode,
			});
		}

		// Generate suggestions for improvement
		if (issues.length === 0) {
			suggestions.push(
				"Code appears to be well-structured and follows best practices"
			);
		} else {
			suggestions.push(
				"Consider addressing the identified issues for better code quality"
			);
		}

		return {
			isValid: !hasError, // isValid is false if any error diagnostic is found
			finalContent: content, // content is not modified by this method
			issues,
			suggestions,
		};
	}

	/**
	 * Analyze file structure for modification context
	 */
	private async _analyzeFileStructure(
		filePath: string,
		content: string
	): Promise<FileStructureAnalysis> {
		const lines = content.split("\n");
		const structure: FileStructureAnalysis = {
			imports: [],
			exports: [],
			functions: [],
			classes: [],
			variables: [],
			comments: [],
		};

		for (let i = 0; i < lines.length; i++) {
			const line = lines[i].trim();

			if (line.startsWith("import ")) {
				structure.imports.push({ line: i + 1, content: line });
			} else if (line.startsWith("export ")) {
				structure.exports.push({ line: i + 1, content: line });
			} else if (line.includes("function ") || line.includes("=>")) {
				structure.functions.push({ line: i + 1, content: line });
			} else if (line.includes("class ")) {
				structure.classes.push({ line: i + 1, content: line });
			} else if (
				line.includes("const ") ||
				line.includes("let ") ||
				line.includes("var ")
			) {
				structure.variables.push({ line: i + 1, content: line });
			} else if (line.startsWith("//") || line.startsWith("/*")) {
				structure.comments.push({ line: i + 1, content: line });
			}
		}

		return structure;
	}

	/**
	 * Formats successful change sets into a concise string for AI prompts.
	 * Limits output to the last 3 change sets and 3 changes per set.
	 * @param changeSets An array of RevertibleChangeSet.
	 * @returns A formatted string summary of recent changes.
	 */
	private _formatSuccessfulChangesForPrompt(
		changeSets: RevertibleChangeSet[]
	): string {
		if (!changeSets || changeSets.length === 0) {
			return "";
		}

		const recentChangeSets = changeSets.slice(-3); // Get last 3 change sets
		let formattedHistory =
			"--- Recent Successful Project Changes (Context for AI) ---\n";

		for (const changeSet of recentChangeSets) {
			const date = new Date(changeSet.timestamp).toLocaleString();
			formattedHistory += `\n**Plan Executed on ${date} (ID: ${changeSet.id.substring(
				0,
				8
			)})**\n`;
			if (changeSet.planSummary) {
				// Changed from changeSet.summary
				formattedHistory += `Summary: ${changeSet.planSummary}\n`; // Changed from changeSet.summary
			}
			formattedHistory += `Changes:\n`;
			const limitedChanges = changeSet.changes.slice(0, 3); // Limit to last 3 changes per set
			for (const change of limitedChanges) {
				formattedHistory += `- **${change.changeType.toUpperCase()}**: \`${
					change.filePath
				}\` - ${change.summary.split("\n")[0]}\n`;
			}
			if (changeSet.changes.length > 3) {
				formattedHistory += `  ...and ${
					changeSet.changes.length - 3
				} more changes.\n`;
			}
		}
		formattedHistory += "\n--- End Recent Successful Project Changes ---\n";
		return formattedHistory;
	}

	/**
	 * Generate modification with enhanced context
	 */
	private async _generateModification(
		filePath: string,
		modificationPrompt: string,
		currentContent: string,
		context: EnhancedGenerationContext, // MODIFIED: fileAnalysis now part of context
		modelName: string,
		streamId: string,
		token?: vscode.CancellationToken,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<string> {
		const enhancedPrompt = createEnhancedModificationPrompt(
			// Replaced `this._createEnhancedModificationPrompt`
			filePath,
			modificationPrompt,
			currentContent,
			context
		);

		try {
			const rawContent = await this.aiRequestService.generateWithRetry(
				[{ text: enhancedPrompt }], // Modified: Wrap prompt string in HistoryEntryPart array
				modelName,
				undefined,
				"enhanced file modification",
				undefined,
				{
					onChunk: async (chunk: string) => {
						this.postMessageToWebview({
							type: "codeFileStreamChunk",
							value: { streamId: streamId, filePath: filePath, chunk: chunk },
						});
						if (onCodeChunkCallback) {
							await onCodeChunkCallback(chunk);
						}
					},
				},
				token
			);
			return cleanCodeOutput(rawContent);
		} catch (error: any) {
			throw error;
		}
	}

	/**
	 * Validate and refine modification
	 */
	private async _validateAndRefineModification(
		filePath: string,
		originalContent: string,
		modifiedContent: string,
		context: EnhancedGenerationContext, // MODIFIED: Change context type
		modelName: string,
		streamId: string,
		token?: vscode.CancellationToken,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<CodeValidationResult> {
		// Check if the modification is reasonable
		const diffAnalysis = this._analyzeDiff(originalContent, modifiedContent);

		if (diffAnalysis.isReasonable) {
			const validation = await this._validateCode(filePath, modifiedContent);
			return {
				isValid: validation.isValid,
				finalContent: modifiedContent,
				issues: validation.issues,
				suggestions: validation.suggestions,
			};
		}

		// If the modification seems unreasonable, try to refine it
		const refinedContent = await createRefineModificationPrompt(
			// Replaced `await this._refineModification(...)`
			filePath,
			originalContent,
			modifiedContent,
			diffAnalysis.issues,
			context
		);

		const finalValidation = await this._validateCode(filePath, refinedContent);

		return {
			isValid: finalValidation.isValid,
			finalContent: refinedContent,
			issues: finalValidation.issues,
			suggestions: finalValidation.suggestions,
		};
	}

	/**
	 * Analyze the diff between original and modified content
	 */
	private _analyzeDiff(original: string, modified: string): DiffAnalysis {
		const originalLines = original.split("\n");
		const modifiedLines = modified.split("\n");

		const issues: string[] = [];
		let isReasonable = true;

		// Check if the modification is too drastic
		const originalLength = originalLines.length;
		const modifiedLength = modifiedLines.length;
		const changeRatio =
			originalLength === 0
				? modifiedLength > 0
					? 1
					: 0
				: Math.abs(modifiedLength - originalLength) / originalLength;

		if (changeRatio > 0.8) {
			issues.push(
				"Modification seems too drastic - consider a more targeted approach"
			);
			isReasonable = false;
		}

		// Check if essential structure is preserved
		const originalImports = originalLines.filter((line) =>
			line.trim().startsWith("import")
		);
		const modifiedImports = modifiedLines.filter((line) =>
			line.trim().startsWith("import")
		);

		if (originalImports.length > 0 && modifiedImports.length === 0) {
			issues.push("All imports were removed - this may be incorrect");
			isReasonable = false;
		}

		return {
			isReasonable,
			issues,
			changeRatio,
		};
	}

	/**
	 * Original full file modification method (fallback)
	 */
	private async _modifyFileContentFull(
		filePath: string,
		modificationPrompt: string,
		currentContent: string,
		context: EnhancedGenerationContext, // MODIFIED: Change context type
		modelName: string,
		streamId: string,
		token?: vscode.CancellationToken,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<{ content: string; validation: CodeValidationResult }> {
		// Step 1: Analyze current file structure and dependencies
		const fileAnalysis = await this._analyzeFileStructure(
			filePath,
			currentContent
		);

		// MODIFIED: Create a new context object that includes fileStructureAnalysis and successfulChangeHistory
		const contextWithAllAnalysis: EnhancedGenerationContext = {
			...context,
			fileStructureAnalysis: fileAnalysis,
			successfulChangeHistory: this._formatSuccessfulChangesForPrompt(
				this.changeLogger.getCompletedPlanChangeSets()
			), // NEW: Populate history
		};

		// Step 2: Generate modification with enhanced context
		const modifiedContent = await this._generateModification(
			filePath,
			modificationPrompt,
			currentContent,
			contextWithAllAnalysis, // MODIFIED: Pass the new context object
			modelName,
			streamId,
			token,
			onCodeChunkCallback
		);

		// Step 3: Validate and refine the modification
		const validation = await this._validateAndRefineModification(
			filePath,
			currentContent,
			modifiedContent,
			contextWithAllAnalysis, // MODIFIED: Pass the new context object
			modelName,
			streamId,
			token,
			onCodeChunkCallback
		);

		return {
			content: validation.finalContent,
			validation: {
				...validation,
			},
		};
	}

	/**
	 * Heuristically determines if the AI's raw text output is likely an error message
	 * instead of valid code/content.
	 * @param content The raw string content generated by the AI.
	 * @returns True if the content is likely an error message, false otherwise.
	 */
	private _isAIOutputLikelyErrorMessage(content: string): boolean {
		const lowerContent = content.toLowerCase().trim();

		// Common phrases indicating an AI error or inability to perform a task
		const errorPhrases = [
			"i am sorry",
			"i'm sorry",
			"i cannot fulfill this request",
			"i encountered an error",
			"i ran into an issue",
			"an error occurred",
			"i am unable to provide",
			"please try again",
			"i couldn't generate",
			"i'm having trouble",
			"error:",
			"failure:",
			"exception:",
			"i can't",
			"i am not able to",
			"as an ai model", // Often precedes an explanation for not being able to do something
			"i lack the ability to",
			"insufficient information",
			"invalid request",
			"not enough context",
		];

		// Common system/API error phrases that might be passed through
		const systemErrorPhrases = [
			"access denied",
			"file not found",
			"permission denied",
			"timeout",
			"rate limit",
			"quota exceeded",
			"server error",
			"api error",
		];

		// Combine all phrases
		const allErrorPhrases = [...errorPhrases, ...systemErrorPhrases];

		if (allErrorPhrases.some((phrase) => lowerContent.includes(phrase))) {
			return true;
		}

		// Heuristic for very short content that looks like an "error"
		// E.g., if it's less than 200 characters and contains keywords like "error", "fail", "issue"
		if (
			content.length < 200 &&
			(lowerContent.includes("error") ||
				lowerContent.includes("fail") ||
				lowerContent.includes("issue"))
		) {
			return true;
		}

		// Safety net: check for markdown code blocks that explicitly contain error-like text.
		// This is for cases where markdown stripping might fail or AI incorrectly wraps an an error in a code block.
		const markdownErrorPattern =
			/(?:[a-zA-Z0-9]+)?\s*(error|fail|exception|apology|i am sorry)[\s\S]*?/i;
		if (markdownErrorPattern.test(content)) {
			return true;
		}

		return false;
	}

	/**
	 * Creates a unique string identifier for a CodeIssue.
	 * Used to compare issues and find newly introduced ones.
	 */
	private _getIssueIdentifier(issue: CodeIssue): string {
		return `${issue.message}|${issue.line}|${issue.type}|${issue.severity}|${
			issue.code ?? ""
		}`;
	}

	/**
	 * Identifies issues present in `newIssues` that were not in `originalIssues`.
	 */
	private _getIssuesIntroduced(
		originalIssues: CodeIssue[],
		newIssues: CodeIssue[]
	): CodeIssue[] {
		const originalIssueSet = new Set<string>(
			originalIssues.map(this._getIssueIdentifier)
		);
		return newIssues.filter(
			(issue) => !originalIssueSet.has(this._getIssueIdentifier(issue))
		);
	}

	/**
	 * Compares two lists of `CodeIssue` objects by checking issue message, type, and line number similarity.
	 * Returns `true` if they are substantially similar, indicating a potential cycle, and `false` otherwise.
	 */
	private _areIssuesSimilar(
		issues1: CodeIssue[],
		issues2: CodeIssue[]
	): boolean {
		if (issues1.length !== issues2.length) {
			return false;
		}

		if (issues1.length === 0 && issues2.length === 0) {
			return true; // Both empty, considered similar
		}

		const set1 = new Set<string>(issues1.map(this._getIssueIdentifier));
		const set2 = new Set<string>(issues2.map(this._getIssueIdentifier));

		if (set1.size !== set2.size) {
			return false;
		}

		for (const id of set1) {
			if (!set2.has(id)) {
				return false;
			}
		}

		return true;
	}

	/**
	 * Detects if the AI is stuck in an oscillation (repeatedly failing to resolve similar issues).
	 * Checks `context.recentCorrectionAttemptOutcomes` for recurring similar issues.
	 * @param context The current enhanced generation context.
	 * @param currentIssuesCount The number of issues before the current failed correction attempt.
	 * @param correctedIssuesCount The number of issues after the current failed correction attempt.
	 * @returns `true` if an oscillation is detected, `false` otherwise.
	 */
	private async _detectOscillation(
		context: EnhancedGenerationContext,
		currentIssuesCount: number, // Not directly used in current simple logic, but can be for more complex heuristics
		correctedIssuesCount: number // Not directly used in current simple logic, but can be for more complex heuristics
	): Promise<boolean> {
		const recentOutcomes = context.recentCorrectionAttemptOutcomes;

		if (!recentOutcomes || recentOutcomes.length < 2) {
			return false; // Need at least two attempts to detect a pattern
		}

		// Check if the last two attempts both failed and left similar issues remaining
		const lastOutcome = recentOutcomes[recentOutcomes.length - 1];
		const secondLastOutcome = recentOutcomes[recentOutcomes.length - 2];

		if (
			!lastOutcome.success &&
			!secondLastOutcome.success &&
			this._areIssuesSimilar(
				lastOutcome.issuesRemaining,
				secondLastOutcome.issuesRemaining
			)
		) {
			// Basic oscillation detected: last two failed attempts left the same set of issues
			return true;
		}

		// More complex oscillation detection: e.g., if the issues count alternates but never resolves,
		// or if a specific issue consistently re-appears.
		// For now, the simple "same issues remaining after two failures" is sufficient.
		return false;
	}

	/**
	 * Generate content with real-time feedback loop
	 */
	private async _generateWithRealTimeFeedback(
		filePath: string,
		generatePrompt: string,
		context: EnhancedGenerationContext, // MODIFIED: Change context type
		modelName: string,
		streamId: string,
		token?: vscode.CancellationToken,
		feedbackCallback?: (feedback: RealTimeFeedback) => void,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<{ content: string; validation: CodeValidationResult }> {
		let currentContent = "";
		let iteration = 0;
		let totalIssues = 0;
		let resolvedIssues = 0;

		// Initialize context properties that will be updated in the loop
		let currentContext: EnhancedGenerationContext = {
			...context,
			lastFailedCorrectionDiff: undefined,
			successfulChangeHistory: this._formatSuccessfulChangesForPrompt(
				this.changeLogger.getCompletedPlanChangeSets()
			),
			lastCorrectionAttemptOutcome: undefined, // NEW: Initialize as undefined
			recentCorrectionAttemptOutcomes: [], // NEW: Initialize as empty array
			isOscillating: false, // NEW: Initialize as false
		};

		this._sendFeedback(feedbackCallback, {
			stage: "initialization",
			message: "Starting code generation with real-time validation...",
			issues: [],
			suggestions: [
				"Analyzing project context",
				"Preparing generation strategy",
			],
			progress: 0,
		});

		try {
			this._sendFeedback(feedbackCallback, {
				stage: "generation",
				message: "Generating initial code structure...",
				issues: [],
				suggestions: ["Creating file structure", "Adding imports"],
				progress: 20,
			});

			// Analyze file structure *before* initial content generation, as it's needed for the prompt
			currentContext.fileStructureAnalysis = await this._analyzeFileStructure(
				filePath,
				"" // Initial content is empty, so analysis is based on surrounding context/empty file.
			);

			currentContent = await this._generateInitialContent(
				filePath,
				generatePrompt,
				currentContext, // Use updated context for initial generation
				modelName,
				streamId,
				token,
				onCodeChunkCallback
			);

			await DiagnosticService.waitForDiagnosticsToStabilize(
				vscode.Uri.file(filePath),
				token,
				5000,
				100
			);

			while (iteration < this.config.maxFeedbackIterations!) {
				if (token?.isCancellationRequested) {
					throw new Error("Operation cancelled");
				}

				iteration++;
				this._sendFeedback(feedbackCallback, {
					stage: "validation",
					message: `Validating code (iteration ${iteration}/${this.config.maxFeedbackIterations})...`,
					issues: [],
					suggestions: [
						"Checking syntax",
						"Validating imports",
						"Analyzing structure",
					],
					progress: 20 + iteration * 15,
				});

				const currentContentBeforeCorrectionAttempt = currentContent;

				const validation = await this._validateCode(filePath, currentContent);
				const currentIssues = validation.issues.length;

				// Always update file structure and successful change history for current context within the loop
				currentContext.fileStructureAnalysis = await this._analyzeFileStructure(
					filePath,
					currentContent
				);
				currentContext.successfulChangeHistory =
					this._formatSuccessfulChangesForPrompt(
						this.changeLogger.getCompletedPlanChangeSets()
					);

				// NEW: Refresh error-focused context if there are issues BEFORE applying corrections
				if (currentIssues > 0) {
					currentContext = await this._refreshErrorFocusedContext(
						filePath,
						currentContent,
						validation.issues,
						currentContext,
						token
					);
				}

				if (currentIssues === 0) {
					this._sendFeedback(feedbackCallback, {
						stage: "completion",
						message: "Code generation completed successfully!",
						issues: [],
						suggestions: validation.suggestions,
						progress: 100,
					});

					currentContext.lastFailedCorrectionDiff = undefined; // Clear diff on success
					currentContext.lastCorrectionAttemptOutcome = undefined; // NEW: Clear outcome on success
					currentContext.recentCorrectionAttemptOutcomes = undefined; // NEW: Clear recent outcomes on success
					currentContext.isOscillating = undefined; // NEW: Clear oscillation status on success
					return {
						content: currentContent,
						validation: {
							...validation,
							finalContent: currentContent,
							iterations: iteration,
							totalIssues: totalIssues,
							resolvedIssues: resolvedIssues,
						},
					};
				}

				totalIssues += currentIssues;

				this._sendFeedback(feedbackCallback, {
					stage: "correction",
					message: `Found ${currentIssues} VS Code-reported compilation/linting issues, applying corrections...`,
					issues: validation.issues,
					suggestions: [
						"Fixing syntax errors",
						"Correcting imports",
						"Improving structure",
					],
					progress: 20 + iteration * 15,
				});

				const correctedContent = await this._applyRealTimeCorrections(
					filePath,
					currentContent,
					validation.issues,
					currentContext, // Pass updated context (potentially refreshed)
					modelName,
					streamId,
					token,
					onCodeChunkCallback
				);

				await DiagnosticService.waitForDiagnosticsToStabilize(
					vscode.Uri.file(filePath),
					token,
					5000,
					100
				);

				const correctedValidation = await this._validateCode(
					filePath,
					correctedContent
				);
				const correctedIssues = correctedValidation.issues.length;

				if (correctedIssues < currentIssues) {
					resolvedIssues += currentIssues - correctedIssues;
					currentContent = correctedContent;
					currentContext.lastFailedCorrectionDiff = undefined; // Clear diff on improvement
					currentContext.lastCorrectionAttemptOutcome = undefined; // NEW: Clear outcome on improvement
					currentContext.recentCorrectionAttemptOutcomes = undefined; // NEW: Clear recent outcomes on improvement
					currentContext.isOscillating = undefined; // NEW: Clear oscillation status on improvement

					this._sendFeedback(feedbackCallback, {
						stage: "improvement",
						message: `Resolved ${
							currentIssues - correctedIssues
						} issues (${correctedIssues} remaining)...`,
						issues: correctedValidation.issues,
						suggestions: correctedValidation.suggestions,
						progress: 20 + iteration * 15,
					});
				} else if (correctedIssues >= currentIssues) {
					// No improvement or made things worse, capture diff and try alternative approach
					// Determine issues introduced by this specific attempt
					const issuesIntroduced = this._getIssuesIntroduced(
						validation.issues,
						correctedValidation.issues
					);

					// Determine failure type based on issue counts
					let failureType: CorrectionAttemptOutcome["failureType"];
					if (correctedIssues > currentIssues) {
						failureType = "new_errors_introduced";
					} else {
						failureType = "no_improvement";
					}

					// Create CorrectionAttemptOutcome for the current failed attempt
					const currentFailedOutcome: CorrectionAttemptOutcome = {
						success: false, // Since no improvement or worse
						iteration: iteration,
						originalIssuesCount: currentIssues,
						issuesAfterAttemptCount: correctedIssues,
						issuesRemaining: correctedValidation.issues,
						issuesIntroduced: issuesIntroduced,
						relevantDiff: "", // Will be populated by createAIFailureAnalysisPrompt
						aiFailureAnalysis: "", // Will be filled below
						failureType: failureType,
					};

					// Initialize recentCorrectionAttemptOutcomes if it doesn't exist
					if (!currentContext.recentCorrectionAttemptOutcomes) {
						currentContext.recentCorrectionAttemptOutcomes = [];
					}
					// Add the current failed outcome to the history
					currentContext.recentCorrectionAttemptOutcomes.push(
						currentFailedOutcome
					);
					// Trim the history to the fixed size
					if (
						currentContext.recentCorrectionAttemptOutcomes.length >
						this.MAX_OSCILLATION_HISTORY_SIZE
					) {
						currentContext.recentCorrectionAttemptOutcomes.shift();
					}

					// Detect oscillation based on the updated history
					currentContext.isOscillating = await this._detectOscillation(
						currentContext,
						currentIssues,
						correctedIssues
					);

					// NEW: Refresh error-focused context again before alternative corrections
					const contextForAlternative = await this._refreshErrorFocusedContext(
						filePath,
						correctedContent, // Use correctedContent for refreshing context as it's the current state
						correctedValidation.issues, // Use the issues after the correction attempt
						currentContext, // Pass the currentContext which now includes oscillation status and recent outcomes
						token
					);
					currentContext = contextForAlternative; // Crucially update currentContext

					// Generate AI failure analysis, passing current context details including oscillation status
					const aiFailureAnalysis = await createAIFailureAnalysisPrompt(
						// Replaced `await this._generateAIFailureAnalysis(...)`
						filePath,
						currentContentBeforeCorrectionAttempt,
						correctedContent,
						validation.issues,
						correctedValidation.issues,
						iteration,
						currentContext.recentCorrectionAttemptOutcomes,
						currentContext.isOscillating
					);

					// Update the currentFailedOutcome with the generated analysis
					currentFailedOutcome.aiFailureAnalysis = aiFailureAnalysis;
					// Update relevant diff in outcome object. The prompt now uses generateFileChangeSummary internally.
					const { formattedDiff } = await generateFileChangeSummary(
						currentContentBeforeCorrectionAttempt,
						correctedContent,
						filePath
					);
					currentFailedOutcome.relevantDiff = formattedDiff;

					// Assign the fully populated outcome to lastCorrectionAttemptOutcome
					currentContext.lastCorrectionAttemptOutcome = currentFailedOutcome;

					// Set lastFailedCorrectionDiff to undefined as new outcome object replaces its function
					currentContext.lastFailedCorrectionDiff = undefined;

					this._sendFeedback(feedbackCallback, {
						stage: "alternative",
						message:
							"Correction did not improve the situation, trying alternative approach...",
						issues: validation.issues,
						suggestions: ["Using different strategy", "Analyzing patterns"],
						progress: 20 + iteration * 15,
					});

					const alternativeContent = await createAlternativeCorrectionPrompt(
						// Replaced `await this._applyAlternativeCorrections(...)`
						filePath,
						correctedContent, // Pass the content AFTER the failed attempt
						correctedValidation.issues, // Pass the issues AFTER the failed attempt
						currentContext // Pass the updated currentContext
					);

					await DiagnosticService.waitForDiagnosticsToStabilize(
						vscode.Uri.file(filePath),
						token,
						5000,
						100
					);

					const alternativeValidation = await this._validateCode(
						filePath,
						alternativeContent
					);

					if (alternativeValidation.issues.length < currentIssues) {
						currentContent = alternativeContent;
						resolvedIssues +=
							currentIssues - alternativeValidation.issues.length;
						currentContext.lastFailedCorrectionDiff = undefined; // Clear diff on successful alternative
						currentContext.lastCorrectionAttemptOutcome = undefined; // NEW: Clear outcome on successful alternative
						currentContext.recentCorrectionAttemptOutcomes = undefined; // NEW: Clear recent outcomes on successful alternative
						currentContext.isOscillating = undefined; // NEW: Clear oscillation status on successful alternative
					} else {
						// Still no improvement with alternative approach, break loop
						this._sendFeedback(feedbackCallback, {
							stage: "revert",
							message:
								"Alternative correction failed or made issues worse. Stopping automatic corrections.",
							issues: validation.issues,
							suggestions: [
								"Manual review recommended",
								"Consider providing more context",
							],
							progress: 20 + iteration * 15,
						});
						break; // Break to avoid infinite loop
					}
				}
			}

			// Final validation after loop exits
			const finalValidation = await this._validateCode(
				filePath,
				currentContent
			);

			this._sendFeedback(feedbackCallback, {
				stage: "final",
				message: `Code generation completed with ${finalValidation.issues.length} remaining issues`,
				issues: finalValidation.issues,
				suggestions: finalValidation.suggestions,
				progress: 100,
			});

			return {
				content: currentContent,
				validation: {
					...finalValidation,
					finalContent: currentContent,
					iterations: iteration,
					totalIssues: totalIssues,
					resolvedIssues: resolvedIssues,
				},
			};
		} catch (error) {
			this._sendFeedback(feedbackCallback, {
				stage: "error",
				message: `Code generation failed: ${
					error instanceof Error ? error.message : String(error)
				}`,
				issues: [],
				suggestions: [
					"Check error details in output",
					"Try again with different approach",
				],
				progress: 100,
			});

			throw error;
		}
	}

	/**
	 * Apply real-time corrections based on validation issues
	 */
	private async _applyRealTimeCorrections(
		filePath: string,
		content: string,
		issues: CodeIssue[],
		context: EnhancedGenerationContext, // MODIFIED: Change context type
		modelName: string,
		streamId: string,
		token?: vscode.CancellationToken,
		onCodeChunkCallback?: (chunk: string) => Promise<void> | void
	): Promise<string> {
		const syntaxIssues = issues.filter((i) => i.type === "syntax");
		const importIssues = issues.filter((i) => i.type === "unused_import");
		const bestPracticeIssues = issues.filter((i) => i.type === "best_practice");
		const securityIssues = issues.filter((i) => i.type === "security");
		const otherIssues = issues.filter((i) => i.type === "other");

		let correctedContent = content;
		const languageId = getLanguageId(path.extname(filePath)); // Get languageId once

		// Apply corrections in order of priority
		if (syntaxIssues.length > 0) {
			correctedContent = await createSyntaxCorrectionPrompt(
				// Replaced `await this._correctSyntaxIssues(...)`
				filePath,
				correctedContent,
				syntaxIssues,
				context
			);
		}

		if (token?.isCancellationRequested) {
			throw new Error("Operation cancelled");
		}

		if (importIssues.length > 0) {
			correctedContent = await createImportCorrectionPrompt(
				// Replaced `await this._correctImportIssues(...)`
				filePath,
				correctedContent,
				importIssues,
				context
			);
		}

		if (token?.isCancellationRequested) {
			throw new Error("Operation cancelled");
		}

		// Combine best_practice and general 'other' issues, as they might stem from general diagnostics
		const combinedPracticeAndOtherIssues = [
			...bestPracticeIssues,
			...otherIssues,
		];
		if (combinedPracticeAndOtherIssues.length > 0) {
			correctedContent = await createPracticeCorrectionPrompt(
				// Replaced `await this._correctPracticeIssues(...)`
				filePath,
				correctedContent,
				combinedPracticeAndOtherIssues, // Pass combined issues
				context
			);
		}

		if (token?.isCancellationRequested) {
			throw new Error("Operation cancelled");
		}

		// Explicitly call _correctSecurityIssues, even if securityIssues array is empty based on current _validateCode mapping
		if (securityIssues.length > 0) {
			// Keep this check, though it might be empty
			correctedContent = await createSecurityCorrectionPrompt(
				// Replaced `await this._correctSecurityIssues(...)`
				filePath,
				correctedContent,
				securityIssues, // Will be empty unless `_validateCode` explicitly maps to "security"
				context
			);
		}

		if (token?.isCancellationRequested) {
			throw new Error("Operation cancelled");
		}

		// Re-validate after primary corrections, if issues persist, then _applyAlternativeCorrections will be called
		// by _generateWithRealTimeFeedback. No need to call it here directly.
		return correctedContent;
	}

	/**
	 * Send feedback to callback if provided
	 */
	private _sendFeedback(
		callback?: (feedback: RealTimeFeedback) => void,
		feedback?: RealTimeFeedback
	): void {
		if (callback && feedback) {
			try {
				callback(feedback);
			} catch (error) {
				console.warn("Error in feedback callback:", error);
			}
		}
	}

	/**
	 * Heuristically determines if the user's prompt indicates an intent for a major rewrite or overhaul.
	 * @param prompt The user's input prompt string.
	 * @param filePath The path of the file being generated/modified (optional, for file-specific keywords).
	 * @returns True if rewrite intent is detected, false otherwise.
	 */
	private _isRewriteIntentDetected(prompt: string, filePath?: string): boolean {
		const lowerPrompt = prompt.toLowerCase();
		const rewriteKeywords = [
			"rewrite",
			"replace entirely",
			"generate from scratch",
			"completely change",
			"full overhaul",
			"start fresh",
			"reimplement",
			"rebuild",
			"design from scratch",
			"new implementation",
			"complete refactor",
		];

		// Check for general rewrite keywords
		if (rewriteKeywords.some((keyword) => lowerPrompt.includes(keyword))) {
			return true;
		}

		// Check for specific "completely change file X" pattern
		if (filePath) {
			const fileBaseName = path.basename(filePath).toLowerCase();
			if (
				lowerPrompt.includes(`completely change file ${fileBaseName}`) ||
				lowerPrompt.includes(`completely change this file`) ||
				lowerPrompt.includes(`rewrite file ${fileBaseName}`) ||
				lowerPrompt.includes(`rewrite this file`)
			) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Refreshes the EnhancedGenerationContext with an error-focused perspective,
	 * rebuilding project context primarily based on current issues.
	 * @param filePath The path of the file currently being processed.
	 * @param currentContent The current content of the file.
	 * @param currentIssues A list of code issues reported for the current content.
	 * @param currentContext The existing EnhancedGenerationContext.
	 * @param token An optional cancellation token.
	 * @returns A new, refreshed EnhancedGenerationContext focused on the errors, or the original context if no issues or an error occurs.
	 */
	private async _refreshErrorFocusedContext(
		filePath: string,
		currentContent: string,
		currentIssues: CodeIssue[],
		currentContext: EnhancedGenerationContext,
		token?: vscode.CancellationToken
	): Promise<EnhancedGenerationContext> {
		if (currentIssues.length === 0) {
			return currentContext;
		}

		try {
			const languageId = getLanguageId(path.extname(filePath));
			const documentUri = vscode.Uri.file(filePath);

			// Construct a minimal editor context for refresh, assuming no specific selection is needed
			// as we are focusing on general file-level issues.
			const editorContextForRefresh = {
				filePath: filePath,
				fullText: currentContent,
				languageId: languageId,
				documentUri: documentUri,
				// A minimal range to satisfy the type, as no specific selection is tied to all issues
				selection: new vscode.Range(0, 0, 0, 0),
				instruction: "",
				selectedText: "",
			};

			// Format currentIssues into a focused diagnostic string for context building
			const formattedDiagnosticsString = formatGroupedIssuesForPrompt(
				groupAndPrioritizeIssues(
					currentIssues,
					this.issueTypeOrder,
					this.severityOrder
				),
				languageId,
				currentContent,
				this.issueTypeOrder,
				this.severityOrder,
				getCodeSnippet
			);

			// Call contextService.buildProjectContext with the formatted diagnostics
			const refreshResult = await this.contextService.buildProjectContext(
				token,
				undefined, // userRequest is not applicable for error-focused refresh
				editorContextForRefresh,
				formattedDiagnosticsString,
				{ useAISelectionCache: false, enablePerformanceMonitoring: false }
			);

			// Create newEnhancedGenerationContext inheriting from currentContext
			// and updating relevant parts from refreshResult.
			const newEnhancedGenerationContext: EnhancedGenerationContext = {
				...currentContext,
				projectContext: refreshResult.contextString,
				relevantFiles: refreshResult.relevantFiles.join("\n"), // relevantFiles is string[] in BuildProjectContextResult
				activeSymbolInfo: refreshResult.activeSymbolDetailedInfo,
				// Ensure successfulChangeHistory is also updated if necessary
				successfulChangeHistory: this._formatSuccessfulChangesForPrompt(
					this.changeLogger.getCompletedPlanChangeSets()
				),
			};

			return newEnhancedGenerationContext;
		} catch (error: any) {
			console.error(
				`[EnhancedCodeGenerator] Error refreshing error-focused context for ${filePath}:`,
				error
			);
			// Log the issue and return the original context to prevent interruption
			return currentContext;
		}
	}
}
